apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-godfs
  labels:
    app: nginx-godfs
spec:
 selector:
  matchLabels:
   app: nginx-godfs
 updateStrategy:
  type: RollingUpdate
 template:
  metadata:
    labels:
     app: nginx-godfs
  spec:
   restartPolicy: Always
   containers:
     - name: nginx-godfs
       image: registry.cn-chengdu.aliyuncs.com/devops_2019/godfs:v1.0
       imagePullPolicy: IfNotPresent
       ports:
       - containerPort: 8095
       #command: ["sleep","111111"]
       command: ["/bin/sh","/dfs/dfs_star.sh"]
       volumeMounts:
       - name: godfs-data-disk
         mountPath: /dfs/files
         subPath: data
       - name: cm-dfs-configfiles
         mountPath: "/config"
   volumes:
   - name: godfs-data-disk
     hostPath:
            path: /data/godfs_data
            type: ""
   - name: cm-dfs-configfiles
     configMap:
       name: cm-dfs-configfiles
       items:
       - key: key-dfs-conf01
         path: cfg.json.bak
   hostNetwork: true
   nodeSelector:
                godfs: "true"