apiVersion: v1
kind: Service
metadata:
 name: nginx-godfs
spec:
 type: NodePort
 ports:
  - name: http
    port: 3699
    nodePort: 36999
  - name: godfsup
    port: 8095
    nodePort: 38095
 selector:
   app: nginx-godfs